### ISSUE TITLE
curl: (35) SSL: CA certificate set, but certificate verification is disabled

### ISSUE THREAD

**Issue by d-Pixie** [gaganpreet/udemy-dl#48]
Got this error on OS X Yosemite with Homebrew installed versions of python, pip and curl (current version as of today).

Tried reinstalling curl with openssl without success.
Added 'insecure' to ~/.curlrc without success.
Reinstalled Python and udemy-dl without success.
Finally I cracked open the code and found the problem quickly on lines 26-28 in download.py

    cert_path = requests.certs.where()
    if cert_path:
        command.extend(['--cacert', cert_path])

Commenting out these lines solves the problem but for a permanent solution I believe that you need this instead (all of curl_dl now):

    def curl_dl(link, filename):
        command = ['curl', '-C', '-', link, '-o', filename]
    
        cert_path = requests.certs.where()
        if cert_path:
            command.extend(['--cacert', cert_path])
        else:
            command.extend(['--insecure'])
        subprocess.call(command)

But Python is not my first language by a long shot so someone familiar with the code and language should probably look at it before I create a pull request :)

**Comment by jricks92** [comment]
I can confirm that the above code fixed the problem in my install.

**Comment by meth984** [comment]
please can help me? 
I have install udemy-pl from pip but when i try to download video from Udemy i have the same you error. Can tell me what i have to do for solve this problem?

**Comment by amarewgs** [comment]
great that helps, I just have updated the download.py file in my installation directory. thanks man!

**Comment by truth1ness** [comment]
Your suggested code worked for me. I think you should go ahead and create a pull request since the developer doesn't seem to be responding to issues, maybe he will see that.

**Comment by truth1ness** [comment]
Your replacement code worked for me. I think you should create a pull request. 

It didn't capture youtube videos, however. This course, https://www.udemy.com/python-gui-programming/  has a mix, the section starting at Lecture 7 is youtube videos and gives the error: 

`Downloading b'001 What are dialogs.mp4'  
[youtube] meaq15EZCfA: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))`

If you could fix that, too, that'd be great. This code gets you the course for free if you want to test it before submitting the pull request: REDDITFREE6

**Comment by zydrick** [comment]
@truth1ness $ pip install youtube-dl

**Comment by truth1ness** [comment]
I have youtube-dl. Is udemy-dl supposed to automatically call youtube-dl to download youtube videos? It just gave me and error and I had to download the rest manually with youtube-dl and sort them into the udemy-dl folders.

**Comment by truth1ness** [comment]
Yes, I have youtube-dl. It looks like from the error that udemy-dl is calling youtube-dl but there is a certificate error. I ended up having to manually use youtube-dl and sorting the files myself. I'm not sure if the certificate problem is related to the one mentioned in this issue.

**Comment by d-Pixie** [comment]
PR open: https://github.com/d-Pixie/udemy-dl/pull/1
